package com.wellness.assistant;

import com.wellness.assistant.model.Habit;
import com.wellness.assistant.storage.DatabaseManager;
import javafx.fxml.FXML;
import javafx.scene.control.ComboBox;
import javafx.stage.Stage;

public class AddHabitController {

    @FXML
    private ComboBox<String> habitTypeComboBox;

    @FXML
    private void initialize() {
        // Populate the combo box with the habit types from your proposal [cite: 112]
        habitTypeComboBox.getItems().addAll(
            "Drink Water",
            "Exercise",
            "Medicine",
            "Eye Rest",
            "Sleep",
            "Mood Tracking"
        );
    }

    @FXML
    private void handleSaveHabit() {
        String selectedType = habitTypeComboBox.getValue();
        if (selectedType != null && !selectedType.isEmpty()) {
            Habit newHabit = new Habit(0, selectedType, "Active"); // ID is 0 as it will be auto-generated by DB
            DatabaseManager.getInstance().addHabit(newHabit);

            // Close the dialog window
            Stage stage = (Stage) habitTypeComboBox.getScene().getWindow();
            stage.close();
        } else {
            // Optional: Show an error message if nothing is selected
            System.err.println("No habit type selected.");
        }
    }
}